/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adeveloperh_androidreversestudy_jni_JNIUtils */

#ifndef _Included_com_adeveloperh_androidreversestudy_jni_JNIUtils
#define _Included_com_adeveloperh_androidreversestudy_jni_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adeveloperh_androidreversestudy_jni_JNIUtils
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adeveloperh_androidreversestudy_jni_JNIUtils_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     com_adeveloperh_androidreversestudy_jni_JNIUtils
 * Method:    getStrFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_adeveloperh_androidreversestudy_jni_JNIUtils_getStrFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_adeveloperh_androidreversestudy_jni_JNIUtils
 * Method:    getSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_adeveloperh_androidreversestudy_jni_JNIUtils_getSum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_adeveloperh_androidreversestudy_jni_JNIUtils
 * Method:    printPersonMsg
 * Signature: (Lcom/adeveloperh/androidreversestudy/jni/bean/Person;)V
 */
JNIEXPORT void JNICALL Java_com_adeveloperh_androidreversestudy_jni_JNIUtils_printPersonMsg
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_adeveloperh_androidreversestudy_jni_JNIUtils
 * Method:    invokeJavaStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adeveloperh_androidreversestudy_jni_JNIUtils_invokeJavaStaticMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
